name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    container: hashicorp/terraform

    env:
      ENVIRONMENT: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init -backend-config="key=frontend/${ENVIRONMENT}/state"
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform apply
        # On push to master, build or change infrastructure according to Terraform configuration files
        #      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
