name: 'PR'

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    name: Deploy
    environment: user
    runs-on: ubuntu-latest
    container: hashicorp/terraform

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      APIGEE_ACCESS_TOKEN: ${{ secrets.APIGEE_ACCESS_TOKEN }}
      APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}

    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          APIGEE_ACCESS_TOKEN=secretvalue
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check
